name: CQ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  code-quality:
    name: Coding standards, code quality and static code analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug
        extensions: dom

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run the linter
      run: composer lint

    - name: Run PHPStan
      run: composer phpstan -- --error-format=github > phpstan.json

    - name: Run psalm
      run: composer psalm --output-format=github

  integration-tests:
    name: Test suite and coverage
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
      - name: Run test suite
        run: vendor/bin/pest

      - name: Run test suite with coverage
        run: |
          if [[ ${{ matrix.php-version }} == '8.1' ]]; then
            vendor/bin/pest --coverage --min=90 --coverage-clover=coverage.xml
          else
            vendor/bin/pest
          fi
